### PR TITLE
XPMToPIX conversion tool added

### PR DESCRIPTION
**Pull request by MickGyver**
A simple XPM to PIX (used by this repo) conversion tool that automatically converts all XPM images in a folder to PIX. Source included.

### CODE REVIEW

**Comment by venice1200** [comment]
Cool, many thanks.
I will try later.

Btw, thanks for your controller sketches!

**Comment by MickGyver** [comment]
And thank you for the nice OLED addon! :)

By the way, the conversion tool should work wherever .NET Core Framework 3.1+ is installed, I have only tested it on Windows though.

**Comment by venice1200** [comment]
Hi,
I saw your 32Pixel PIX's and transformed Arkanoid to my 64' needs.
Do you have to change the i2c2oled script a lot for 32' PIX?

And if we add my 16 Pixel Header + 8 additional Empty Lines on top and to the bottom 
of your 32 Pix Pictures we can use them with the 128x64Pixel Display as well.
I will double check if I get it done with some sort of (PowerShell) Script.

Your conversion tools works fine. I drop my XPM folder onto it, done.

CU

**Comment by MickGyver** [comment]
I didn't need to change too much to get it working with 128x32px screens. I did some small changes to the 64px script also but I'm planning of combining the scripts so height can be set as a variable. You can compare my two scripts with WinMerge or some similar tool to see the difference between them. I will make a pull request when I get it cleaned up.

**Pull request merged**
