### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ahmadexp**

### CODE REVIEW

**Comment by venice1200** [comment]
Thx

**Comment by venice1200** [comment]
I added the temperature options to the configuration part. 
Please double check this section as well.

**Comment by ahmadexp** [comment]
Looks great.
With regards to the fan controller, @antoniavillena and I are looking into an i2c solution to control the fan speed. That way we can write a simple PI controller that can reside on the i2c2oled demon which is reason the temperature and control the fan speed.

**Comment by ahmadexp** [comment]
@venice1200 I wanted to know your opinion about this new idea.
I just finished a patch on the i2c2oled.sh to make it play MIDI files on the MT32 while in the menu.
It stops the music when it goes in the cores and resumes when it comes back.

**Comment by ahmadexp** [comment]
30F3C944-250F-4D0C-8CB2-F7F997CE7749

**Comment by venice1200** [comment]
Nice Idea but I would make a separate Project.

Just read the CORENAME file and react.

**Comment by venice1200** [comment]
Could you make the mt32-pi-ctl programm available for me please?

**Comment by ahmadexp** [comment]
Yeah, I am going to add it to the BGM project

**Comment by ahmadexp** [comment]
@venice1200 
[mt32-pi-ctl.zip](https://github.com/venice1200/MiSTer_i2c2oled/files/9390003/mt32-pi-ctl.zip)

**Pull request merged**
