### PR TITLE
Generate Pix list for viewer

### PR DESCRIPTION
**Pull request by mr-fitzie**
Add a GitHub Actions workflow to generate a list of Pix in the repository. This workflow runs when a new `.pix` file is added to the `Pictures/Pix` directory.

**NOTE** This workflow differs slightly from the tty2oled_Pictures workflow because it commits the data file back to the `main` branch in `Pictures/data_i2c_pix.json` this means that before you commit changes to i2c2oled repo you should always _pull_ the latest changes as the action probably automatically ran and you will be behind a version and need to sync first. If this is annoying, we can create a new orphan `data` branch similar to what we did on the main repo and add the data there.

### CODE REVIEW

**Comment by venice1200** [comment]
I am thinking about moving the i2c2oled pictures to the tty2oled picture repository.
Would this help or make things easier?

**Comment by mr-fitzie** [comment]
That def would make things easier, could just modify the existing workflow there to handle the new format/category

**Comment by venice1200** [comment]
As we don‘t want to mix tty2oled and i2c2oled content, I have created a dedicated repo for the i2c2oled pictures. 
https://github.com/venice1200/MiSTer_i2c2oled_Pictures
Any problems with this?
Cheers

**Comment by mr-fitzie** [comment]
I see the new repo, do you want two separate viewers? With the low number of i2c pictures I was just thinking of splitting them off into a separate category in the existing viewer (as shown in the screenshot in the forum thread). I prefer the idea of a single viewer rather than two. Thoughts?

**Comment by venice1200** [comment]
We don‘t need two viewers, I forgot to say this. Sorry.
The i2c2oled picture repo got already his gh-pages branch.

**Comment by mr-fitzie** [comment]
Action was created in new i2c2oled_Pictures repo

**Pull request closed without merging**
